name: Build and Delivery

# Запуск workflow только на пуш в main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Клонируем репозиторий полностью
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # <- важно, чтобы Docker видел все файлы и коммиты

      # 2️⃣ Логин в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3️⃣ Сборка и публикация Docker образа
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .                 # <- локальная копия репозитория
          file: ./Dockerfile         # <- Dockerfile в корне
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/my-app:latest
          no-cache: true             # <- отключаем кэш, чтобы точно увидеть requirements.txt

