name: Test Python App

on:
  push:
    branches:
      - '**'   # запуск на любой ветке при пуше

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Устанавливаем Python 3.12
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      # 3️⃣ Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi httpx pytest

      # 4️⃣ Запускаем тесты
      - name: Run tests
        run: python -m pytest tests/

